language: python
python: 
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  global:
    secure: "CfqS+5SkXs6b31+D2CpdUoNh25bDhXKmJ7ah0PBP/k8XC65GdCpDKsC+lcAS59xaaxJGoHGr0neQpn8ofkpSWUtnii+eN83kLrDrV25t7s3IwmHfUkPL0L6Sf9N2l67YQQaxhhvjbbSBbWiztTeLK1fGuCu7QaV484WoBUkOmXI="
  matrix: 
    - HTTP_LIBRARY=pycurl
    - HTTP_LIBRARY=requests

before_install: 
  - pip install pep8 
  - if [[ $TRAVIS_PYTHON_VERSION == *2.6* ]]; then pip install unittest2; fi
  - pip install coverage 

install: 
  - pip install $HTTP_LIBRARY 
  - python setup.py install

script:
  - pep8 .
  - coverage run --omit "*test*,*requests*,*curl*,*pkg*" --module tests --verbose
  - coverage report --show-missing

notifications: 
  email: 
  - pineapple.liu@gmail.com
