language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
    - pip install pep8 --use-mirrors
    - "if [[ $TRAVIS_PYTHON_VERSION == *2.6* ]]; then pip install unittest2; fi"
    - pip install coverage --use-mirrors

install:
    - python setup.py install

script:
    - pep8 *.py
    - coverage run --omit "*test*" -m tests --verbose
    - coverage report -m

notifications:
  email:
    - pineapple.liu@gmail.com
